# Generated by Django 3.2.11 on 2022-01-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users_friend',
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
