# Generated by Django 3.2.11 on 2022-01-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
